//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIVLIO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MESSAGE
    {
        public int MESSAGEID { get; set; }
        public int SENDERID { get; set; }
        public int RECEIVERID { get; set; }

        [DataType(DataType.MultilineText)]
        public string MESSAGETEXT { get; set; }
        public string STATUS { get; set; }
        public string Subject { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
